# These are supported funding model platforms
ko_fi: # https://ko-fi.com/oluseyiadeyemo
buy_me_a_coffee: # https://buymeacoffee.com/seyiphysica
contact us for any support and enquiry: # https://www.linkedin/oluseyioluseyi-adeyemo
                                        # https://github.com/Seyigate/gate_Keylogger
                                        
