# These are supported funding model platforms
ko_fi: # https://ko-fi.com/oluseyiadeyemo

buy_me_a_coffee: # https://buymeacoffee.com/seyiphysica
 #<a href="https://www.buymeacoffee.com/seyiphysica" target="_blank"><img src="https://cdn.buymeacoffee.com/buttons/v2/default-yellow.png" alt="Buy Me A Coffee" style="height: 60px !important;width: 217px !important;" ></a>
contact us for any support and enquiry: # https://www.linkedin/oluseyioluseyi-adeyemo
                                        # https://github.com/Seyigate/gate_Keylogger
                                        
